services:
  db:
    build: ./BDD/
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s

  server:
    build: ./Back/
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:3000/api",
          "||",
          "exit",
          "1"
        ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s

  client:
    build: ./Front/
    ports:
      - "8080:8080"
    depends_on:
      server:
        condition: service_completed_successfully
