apiVersion: apps/v1
kind: Deployment
metadata:
  name: mot-backend
  labels:
    name: mot-backend
spec:
  selector:
    matchLabels:
      app: mot-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mot-backend
    spec:
      containers:
        - name: mot-backend-container
          image: jathoosh/mot-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_HOST
              value: mot-db
            - name: DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: mot-backend
  labels:
    app: mot-backend
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: mot-backend